image: vowstar/esp8266

variables: 
    IDF_PATH: "/builds/embedded/ss19/easy-grow/ESP/ESP8266_RTOS_SDK"
    HOME: ${PWD}

envtest:
  script:
    - echo ${IDF_PATH}
    - echo ${PATH}

test:
  before_script:
    - ls 
    - mkdir ESP
    - cd ESP/
    - git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
    - cd ESP8266_RTOS_SDK
    - git reset --hard "d83c9f7866e59dcbb254ce5366c27418d410e84e"
    - ls
    - printenv
    
  script:
    - cd ${HOME}
    - ls
    - make
  only:
    - master
    - feature/ci