image: vowstar/esp8266

variables: 
    IDF_PATH: ${CI_PROJECT_DIR}/ESP/ESP8266_RTOS_SDK

envtest:
  script:
    - echo ${IDF_PATH}
    - echo ${PATH}
    - echo ${CI_PROJECT_DIR}

test:
  before_script:
    - ls 
    - mkdir ESP
    - cd ESP/
    - git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
    - cd ESP8266_RTOS_SDK
    - git checkout "d83c9f7866e59dcbb254ce5366c27418d410e84e"
    - cd ${CI_PROJECT_DIR}/ESP
    - wget "https://dl.espressif.com/dl/xtensa-lx106-elf-osx-1.22.0-92-g8facf4c-5.2.0.tar.gz"
    - tar -xzf "xtensa-lx106-elf-osx-1.22.0-92-g8facf4c-5.2.0.tar.gz"
    - export PATH=$PATH:${CI_PROJECT_DIR}/ESP/xtensa-lx106-elf/bin
    - ls
    - printenv
    
  script:
    - cd ${CI_PROJECT_DIR}
    - ls
    - make
  only:
    - master
    - feature/ci