image: vowstar/esp8266



test:
  before_script:
    - ls 
    - mkdir ESP
    - cd ESP/
    - git clone --recursive https://github.com/espressif/ESP8266_RTOS_SDK.git
    - git reset --hard d83c9f7866e59dcbb254ce5366c27418d410e84e
    - ls
    - printenv
    
  script:
    - make
  only:
    - master
    - feature/ci


