image: mirohero/docker-esp8266

sdk-test:
  script:
    - cd ${CI_PROJECT_DIR}/tests
    - chmod +x sdk-test.sh
    - ./sdk-test.sh

build-test:   
  script:
    - cd ${CI_PROJECT_DIR}
    - make
  only:
    - master
    - dev